Remove all redundant object files
Galaxia5987/Recode2024 pull request #48
Opened 2024-10-21 22:46 UTC by rakrakon

2024-10-22 11:22 UTC, katzuv requested changes

2024-10-22 11:22 UTC, katzuv commented on src/main/kotlin/frc/robot/subsystems/climb/ClimbConstants.kt
> +
You can make this work using `apply`.

2024-10-22 11:22 UTC, katzuv commented on src/main/kotlin/frc/robot/subsystems/conveyor/Conveyor.kt
> +    private val kP = LoggedTunableNumber("Conveyor/kP", GAINS.kP)
Just a side note about tunable numbers: according to https://github.com/Mechanical-Advantage/AdvantageScope/issues/243 it seems that a new feature in AdvantageKit will "allow tuning values while using the AdvantageKit NT mode", so I wouldn't work on these and wait for the beta release.

2024-11-05 13:30 UTC, rakrakon commented on src/main/kotlin/frc/robot/subsystems/climb/ClimbConstants.kt
> +
This is using apply. I think you have it outdated

2024-11-06 15:58 UTC, katzuv approved these changes

2024-11-08 11:48 UTC, closed without merging